const API_BASE = (import.meta.env?.VITE_MPLAD_API_BASE || window.MPLAD_API_BASE || 'https://9swhxvuz7b.execute-api.eu-north-1.amazonaws.com/api').replace(/\/$/, '');
const pageSize = 50;
const resultList = document.querySelector('#resultList');
const loadMoreButton = document.querySelector('#loadMore');
const map = window.MPLAD_MAP;
const mapLayers = [];
const INDIA_CENTER = [22.5, 79];
let projects = [], totalResults = 0, nextOffset = 0, loading = false, facetLoading = false, metricsRequest = 0, searchTimer;
const formatNumber = (value) => Number.isFinite(Number(value)) ? new Intl.NumberFormat('en-IN').format(Number(value)) : '—';
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const formatDate = (value) => { if (!value) return 'Not stated in source'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeZone: 'UTC' }).format(date); };
const value = (id) => document.querySelector(`#${id}`).value;
async function getJson(path, options) { const response = await fetch(`${API_BASE}${path}`, options); if (!response.ok) throw new Error(`API request failed: ${response.status}`); return response.json(); }
function setCatalogStatus(message, healthy = true) { const node = document.querySelector('#catalogStatus'); node.textContent = message; document.querySelector('#statusDot')?.classList.toggle('error', !healthy); }
function currentQuery() { const params = new URLSearchParams(); [['query', document.querySelector('#globalSearch').value.trim()], ['house', value('houseFilter')], ['term', value('termFilter')], ['state', value('stateFilter')], ['district', value('districtFilter')], ['constituency', value('constituencyFilter')], ['category', value('categoryFilter')]].forEach(([key, item]) => { if (item) params.set(key, item); }); return params; }
function fillSelect(id, label, values, selected = '') { const select = document.querySelector(`#${id}`); select.innerHTML = `<option value="">${escapeHtml(label)}</option>${values.map((item) => `<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join('')}`; if ([...select.options].some((option) => option.value === selected)) select.value = selected; }
async function loadFacets() { if (facetLoading) return; facetLoading = true; const selected = Object.fromEntries(['houseFilter','termFilter','stateFilter','districtFilter','constituencyFilter','categoryFilter'].map((id) => [id, value(id)])); try { const { data } = await getJson(`/catalog/facets?${currentQuery()}`); fillSelect('houseFilter', 'All houses', data.houses, selected.houseFilter); fillSelect('termFilter', 'All terms', data.terms, selected.termFilter); fillSelect('stateFilter', 'All States / UTs', data.states, selected.stateFilter); fillSelect('districtFilter', 'All districts', data.districts, selected.districtFilter); fillSelect('constituencyFilter', 'All constituencies', data.constituencies || [], selected.constituencyFilter); fillSelect('categoryFilter', 'All categories', data.categories, selected.categoryFilter); } catch { setCatalogStatus('Source filters unavailable', false); } finally { facetLoading = false; } }
function updateResultsCount() { document.querySelector('#resultsCount').textContent = `${formatNumber(totalResults)} works`; document.querySelector('#resultsRange').textContent = projects.length ? `· showing 1–${formatNumber(projects.length)}` : '· no matching records'; loadMoreButton.hidden = !projects.length || projects.length >= totalResults; loadMoreButton.disabled = loading; loadMoreButton.textContent = projects.length < totalResults ? `Load ${formatNumber(Math.min(pageSize, totalResults - projects.length))} more records` : 'All matching records loaded'; document.querySelector('#scopeNote').textContent = `${formatNumber(totalResults)} source records match this scope. ${value('districtFilter') ? 'District scope applied.' : 'Choose a district to view its complete register.'}`; }
function updateDistrictLink() { const link = document.querySelector('#districtPageLink'); const district = value('districtFilter'); if (!link) return; if (!district) { link.hidden = true; return; } const params = new URLSearchParams({ district }); if (value('stateFilter')) params.set('state', value('stateFilter')); if (value('houseFilter')) params.set('house', value('houseFilter')); if (value('termFilter')) params.set('term', value('termFilter')); link.href = `/district.html?${params}`; link.hidden = false; }
function renderResults() { if (!projects.length) { resultList.innerHTML = '<div class="empty-state">No source records match these filters.<br /><small>Try another village, State/UT, district, term or house.</small></div>'; updateResultsCount(); return; } resultList.innerHTML = `<div class="result-table-wrap"><table class="result-table"><thead><tr><th>Work description</th><th>Location</th><th>House / term</th><th>Status</th><th>Amount</th><th>Record</th></tr></thead><tbody>${projects.map((project) => `<tr><td><strong>${escapeHtml(project.title)}</strong><small>${escapeHtml(project.mp)}</small></td><td><span>${escapeHtml(project.district)}</span><small>${escapeHtml([project.block, project.villageRaw, project.state].filter(Boolean).join(' · '))}</small></td><td><span>${escapeHtml(project.house)}</span><small>${escapeHtml(project.term)}</small></td><td><span class="status-chip"><i></i>${escapeHtml(project.status)}</span><small>${escapeHtml(project.risk)}</small></td><td><strong>${escapeHtml(project.amount)}</strong><small>${escapeHtml(project.category)}</small></td><td><a class="row-action" href="/project.html?id=${encodeURIComponent(project.id)}">View details ↗</a></td></tr>`).join('')}</tbody></table></div>`; updateResultsCount(); }
async function loadCatalog({ append = false } = {}) { if (loading || (append && nextOffset >= totalResults)) return; loading = true; if (!append) { nextOffset = 0; resultList.innerHTML = '<div class="loading-state">Loading source records…</div>'; } const params = currentQuery(); params.set('limit', pageSize); params.set('offset', append ? nextOffset : 0); try { const payload = await getJson(`/projects?${params}`); projects = append ? [...projects, ...payload.data] : payload.data; totalResults = payload.meta.total; nextOffset = payload.meta.offset + payload.meta.count; renderResults(); setCatalogStatus('Source connected'); await refreshMap(); } catch { projects = []; totalResults = 0; resultList.innerHTML = '<div class="empty-state">The source catalogue could not be reached. Check the API deployment.</div>'; setCatalogStatus('Catalogue unavailable', false); updateResultsCount(); } finally { loading = false; updateResultsCount(); } }
async function loadMetrics() { const requestId = ++metricsRequest; try { const { data } = await getJson(`/catalog/metrics?${currentQuery()}`); if (requestId !== metricsRequest) return; document.querySelector('#scopeAllocated').textContent = data.allocatedAmount == null ? 'Not available' : `₹${formatNumber(data.allocatedAmount)}`; document.querySelector('#scopeUsed').textContent = data.expenditureAmount == null ? 'Not available' : `₹${formatNumber(data.expenditureAmount)}`; document.querySelector('#scopeRecommended').textContent = formatNumber(data.worksRecommended); document.querySelector('#scopeSanctioned').textContent = formatNumber(data.worksSanctioned); document.querySelector('#scopeOngoing').textContent = formatNumber(data.worksOngoing); document.querySelector('#scopeCompleted').textContent = formatNumber(data.worksCompleted); document.querySelector('#scopeMetricsNote').textContent = data.note; } catch { document.querySelector('#scopeMetricsNote').textContent = 'Source metrics unavailable.'; } }
async function loadSummary() { try { const { data } = await getJson('/catalog/summary'); document.querySelector('#sourceRecords').textContent = formatNumber(data.total); document.querySelector('#sourceCoverage').textContent = `${formatNumber(data.sourceCoverage)}% attributed`; document.querySelector('#sourceUpdated').textContent = `Through ${formatDate(data.sourceDataThrough)}`; document.querySelector('#sourceDescription').textContent = `${formatNumber(data.total)} records from the live eSAKSHI ingest and cited source snapshot. Terms: ${formatNumber(data.terms['17th Lok Sabha'])} 17th, ${formatNumber(data.terms['18th Lok Sabha'])} 18th, ${formatNumber(data.terms['Rajya Sabha'])} Rajya Sabha.`; } catch { setCatalogStatus('Catalogue unavailable', false); } }
function initializeMap() { if (!map) return; map.setView(INDIA_CENTER, 5); window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '&copy; OpenStreetMap contributors' }).addTo(map); }
async function refreshMap() { if (!map) return; try { const { data } = await getJson(`/map/locations?${currentQuery()}`); mapLayers.splice(0).forEach((layer) => map.removeLayer(layer)); if (!data.points.length) { document.querySelector('#mapStatus').textContent = data.message || data.precision; return; } const bounds = []; data.points.forEach((point) => { const marker = window.L.circleMarker([point.lat, point.lon], { radius: Math.min(18, 7 + Math.log10(point.count + 1) * 4), color: '#005a9c', fillColor: '#ff9933', fillOpacity: .85, weight: 2 }); marker.bindPopup(`<strong>${escapeHtml(point.district)}</strong><br>${formatNumber(point.count)} matching works<br><small>Approximate district location</small>`).addTo(map); mapLayers.push(marker); bounds.push([point.lat, point.lon]); }); map.fitBounds(bounds, { padding: [28, 28], maxZoom: 10 }); document.querySelector('#mapStatus').textContent = `${formatNumber(data.totalMatches)} matching works · ${data.precision}`; } catch { document.querySelector('#mapStatus').textContent = 'Map location service unavailable. The table remains available.'; } }
document.querySelector('#filtersForm').addEventListener('submit', async (event) => { event.preventDefault(); document.querySelector('#explore').scrollIntoView({ behavior: 'smooth', block: 'start' }); await loadCatalog(); await loadMetrics(); });
document.querySelector('#globalSearch').addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(async () => { await loadCatalog(); await loadMetrics(); }, 300); });
document.querySelectorAll('#houseFilter, #termFilter, #stateFilter, #districtFilter, #constituencyFilter, #categoryFilter').forEach((select) => select.addEventListener('change', async () => { updateDistrictLink(); await loadFacets(); await loadCatalog(); await loadMetrics(); }));
document.querySelector('#clearFilters').addEventListener('click', async () => { document.querySelector('#globalSearch').value = ''; ['houseFilter','termFilter','stateFilter','districtFilter','constituencyFilter','categoryFilter'].forEach((id) => { document.querySelector(`#${id}`).value = ''; }); await loadFacets(); await loadCatalog(); await loadMetrics(); });
loadMoreButton.addEventListener('click', () => loadCatalog({ append: true })); document.querySelector('#resetMap').addEventListener('click', () => { map?.setView(INDIA_CENTER, 5); refreshMap(); }); document.querySelectorAll('.view-toggle button').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.view-toggle button').forEach((item) => item.classList.remove('active')); button.classList.add('active'); document.querySelector('.workspace-grid').classList.toggle('table-only', button.dataset.view === 'table'); setTimeout(() => map?.invalidateSize(), 50); }));
const root = document.documentElement; const fontScale = Number(localStorage.getItem('mpworks-font-scale') || 1); root.style.setProperty('--font-scale', fontScale); document.querySelectorAll('[data-font]').forEach((button) => button.addEventListener('click', () => { const current = Number(root.style.getPropertyValue('--font-scale') || 1); const next = button.dataset.font === 'increase' ? Math.min(1.25, current + .1) : button.dataset.font === 'decrease' ? Math.max(.85, current - .1) : 1; root.style.setProperty('--font-scale', next); localStorage.setItem('mpworks-font-scale', next); }));
initializeMap(); updateDistrictLink(); Promise.all([loadFacets(), loadSummary(), loadCatalog(), loadMetrics()]);
