const API_BASE = (import.meta.env?.VITE_MPLAD_API_BASE || window.MPLAD_API_BASE || 'https://mpworks-api-public.onrender.com/api').replace(/\/$/, '');
const pageSize = 50;
const resultList = document.querySelector('#resultList');
const loadMoreButton = document.querySelector('#loadMore');
const map = window.MPLAD_MAP;
const mapLayers = [];
let mapPin = null;
let mapPinLocation = null;
const INDIA_CENTER = [22.5, 79];
let projects = [], totalResults = 0, nextOffset = 0, loading = false, facetLoading = false, metricsRequest = 0, searchTimer;
const formatNumber = (value) => Number.isFinite(Number(value)) ? new Intl.NumberFormat('en-IN').format(Number(value)) : '—';
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const formatDate = (value) => { if (!value) return 'Not stated in source'; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeZone: 'UTC' }).format(date); };
const value = (id) => document.querySelector(`#${id}`).value;
async function getJson(path, options) { const response = await fetch(`${API_BASE}${path}`, options); if (!response.ok) throw new Error(`API request failed: ${response.status}`); return response.json(); }
function setCatalogStatus(message, healthy = true) { const node = document.querySelector('#catalogStatus'); node.textContent = message; document.querySelector('#statusDot')?.classList.toggle('error', !healthy); }
function currentQuery() { const params = new URLSearchParams(); [['query', document.querySelector('#globalSearch').value.trim()], ['house', value('houseFilter')], ['term', value('termFilter')], ['state', value('stateFilter')], ['district', value('districtFilter')], ['constituency', value('constituencyFilter')], ['category', value('categoryFilter')], ['status', value('statusFilter')]].forEach(([key, item]) => { if (item) params.set(key, item); }); return params; }
function fillSelect(id, label, values, selected = '') { const select = document.querySelector(`#${id}`); select.innerHTML = `<option value="">${escapeHtml(label)}</option>${values.map((item) => `<option value="${escapeHtml(item)}">${escapeHtml(item)}</option>`).join('')}`; if ([...select.options].some((option) => option.value === selected)) select.value = selected; }
async function loadFacets() { if (facetLoading) return; facetLoading = true; const selected = Object.fromEntries(['houseFilter','termFilter','stateFilter','districtFilter','constituencyFilter','categoryFilter','statusFilter'].map((id) => [id, value(id)])); try { const { data } = await getJson(`/catalog/facets?${currentQuery()}`); fillSelect('houseFilter', 'All houses', data.houses, selected.houseFilter); fillSelect('termFilter', 'All terms', data.terms, selected.termFilter); fillSelect('stateFilter', 'All States / UTs', data.states, selected.stateFilter); fillSelect('districtFilter', 'All districts', data.districts, selected.districtFilter); fillSelect('constituencyFilter', 'All constituencies', data.constituencies || [], selected.constituencyFilter); fillSelect('categoryFilter', 'All categories', data.categories, selected.categoryFilter); fillSelect('statusFilter', 'All work statuses', data.statuses || ['Recommended', 'Sanctioned', 'Ongoing', 'Completed'], selected.statusFilter); } catch { setCatalogStatus('Source filters unavailable', false); } finally { facetLoading = false; } }
function updateResultsCount() { document.querySelector('#resultsCount').textContent = `${formatNumber(totalResults)} works`; document.querySelector('#resultsRange').textContent = projects.length ? `· showing 1–${formatNumber(projects.length)}` : '· no matching records'; loadMoreButton.hidden = !projects.length || projects.length >= totalResults; loadMoreButton.disabled = loading; loadMoreButton.textContent = projects.length < totalResults ? `Load ${formatNumber(Math.min(pageSize, totalResults - projects.length))} more records` : 'All matching records loaded'; document.querySelector('#scopeNote').textContent = `${formatNumber(totalResults)} source records match this scope. ${value('districtFilter') ? 'District scope applied.' : 'Choose a district to view its complete register.'}`; updateExportLinks(); }
function ensureExportControls() { const toolbar = document.querySelector('.results-toolbar'); if (!toolbar || document.querySelector('#exportControls')) return; toolbar.insertAdjacentHTML('beforeend', '<div id="exportControls" class="export-controls" aria-label="Download current data"><span>Download up to 10,000 matching rows</span><a id="exportCsv" class="small-button" href="#">CSV</a><a id="exportExcel" class="small-button" href="#">Excel</a><a id="exportPdf" class="small-button" href="#">PDF</a></div>'); }
function updateExportLinks() { const query = currentQuery().toString(); ['Csv','Excel','Pdf'].forEach((format) => { const link = document.querySelector(`#export${format}`); if (link) link.href = `${API_BASE}/exports/${format === 'Csv' ? 'csv' : format === 'Excel' ? 'excel' : 'pdf'}?${query}`; }); }
function updateDistrictLink() { const link = document.querySelector('#districtPageLink'); const district = value('districtFilter'); if (!link) return; if (!district) { link.hidden = true; return; } const params = new URLSearchParams({ district }); if (value('stateFilter')) params.set('state', value('stateFilter')); if (value('houseFilter')) params.set('house', value('houseFilter')); if (value('termFilter')) params.set('term', value('termFilter')); link.href = `/district.html?${params}`; link.hidden = false; }
function renderResults() { if (!projects.length) { resultList.innerHTML = '<div class="empty-state">No source records match these filters.<br /><small>Try another village, State/UT, district, term or house.</small></div>'; updateResultsCount(); return; } resultList.innerHTML = `<div class="result-table-wrap"><table class="result-table"><thead><tr><th>Work description</th><th>Location</th><th>House / term</th><th>Status / review index</th><th>Amount</th><th>Record</th></tr></thead><tbody>${projects.map((project) => `<tr><td><strong>${escapeHtml(project.title)}</strong><small>${escapeHtml(project.mp)}</small></td><td><span>${escapeHtml(project.district)}</span><small>${escapeHtml([project.block, project.villageRaw, project.state].filter(Boolean).join(' · '))}</small></td><td><span>${escapeHtml(project.house)}</span><small>${escapeHtml(project.term)}</small></td><td><span class="status-chip"><i></i>${escapeHtml(project.status)}</span><small>Review index: ${escapeHtml(project.riskIndex?.score ?? '—')}/100 · ${escapeHtml(project.riskIndex?.label || 'AI comparison pending')}</small></td><td><strong>${escapeHtml(project.amount)}</strong><small>${escapeHtml(project.category)}</small></td><td><a class="row-action" href="/project.html?id=${encodeURIComponent(project.id)}">View details ↗</a></td></tr>`).join('')}</tbody></table></div>`; updateResultsCount(); }
async function loadCatalog({ append = false } = {}) { if (loading || (append && nextOffset >= totalResults)) return; loading = true; if (!append) { nextOffset = 0; resultList.innerHTML = '<div class="loading-state">Loading source records…</div>'; } const params = currentQuery(); params.set('limit', pageSize); params.set('offset', append ? nextOffset : 0); try { const payload = await getJson(`/projects?${params}`); projects = append ? [...projects, ...payload.data] : payload.data; totalResults = payload.meta.total; nextOffset = payload.meta.offset + payload.meta.count; renderResults(); setCatalogStatus('Source connected'); await refreshMap(); } catch { projects = []; totalResults = 0; resultList.innerHTML = '<div class="empty-state">The source catalogue could not be reached. Check the API deployment.</div>'; setCatalogStatus('Catalogue unavailable', false); updateResultsCount(); } finally { loading = false; updateResultsCount(); } }
async function loadMetrics() { const requestId = ++metricsRequest; try { const { data } = await getJson(`/catalog/metrics?${currentQuery()}`); if (requestId !== metricsRequest) return; document.querySelector('#scopeAllocated').textContent = data.allocatedAmount == null ? 'Not available' : `₹${formatNumber(data.allocatedAmount)}`; document.querySelector('#scopeUsed').textContent = data.expenditureAmount == null ? 'Not available' : `₹${formatNumber(data.expenditureAmount)}`; document.querySelector('#scopeRecommended').textContent = formatNumber(data.worksRecommended); document.querySelector('#scopeSanctioned').textContent = formatNumber(data.worksSanctioned); document.querySelector('#scopeOngoing').textContent = formatNumber(data.worksOngoing); document.querySelector('#scopeCompleted').textContent = formatNumber(data.worksCompleted); document.querySelector('#scopeMetricsNote').textContent = data.note; } catch { document.querySelector('#scopeMetricsNote').textContent = 'Source metrics unavailable.'; } }
async function loadSummary() { try { const { data } = await getJson('/catalog/summary'); document.querySelector('#sourceRecords').textContent = formatNumber(data.total); document.querySelector('#sourceCoverage').textContent = `${formatNumber(data.sourceCoverage)}% attributed`; document.querySelector('#sourceUpdated').textContent = `Through ${formatDate(data.sourceDataThrough)}`; document.querySelector('#sourceDescription').textContent = `${formatNumber(data.total)} records from the live eSAKSHI ingest and cited source snapshot. Terms: ${formatNumber(data.terms['17th Lok Sabha'])} 17th, ${formatNumber(data.terms['18th Lok Sabha'])} 18th, ${formatNumber(data.terms['Rajya Sabha'])} Rajya Sabha.`; } catch { setCatalogStatus('Catalogue unavailable', false); } }
async function setMapPin(latitude, longitude) { if (!map) return; if (mapPin) map.removeLayer(mapPin); mapPin = window.L.marker([latitude, longitude], { draggable: true }).addTo(map); mapPin.bindPopup('Looking up this area…').openPopup(); const update = async (lat, lon) => { mapPinLocation = { lat, lon }; try { const { data } = await getJson(`/map/reverse?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`); mapPinLocation = { ...data, lat, lon }; mapPin?.setPopupContent(`<strong>${escapeHtml(data.area || data.district || 'Pinned area')}</strong><br>${escapeHtml(data.displayName || '')}<br><small>${escapeHtml(data.state || '')} · ${escapeHtml(data.district || '')} · approximate</small>`).openPopup(); document.querySelector('#mapStatus').textContent = `Pinned: ${data.displayName || data.area || 'selected area'} · ${data.precision || 'approximate'}`; document.querySelector('#applyMapPin').hidden = false; document.querySelector('#clearMapPin').hidden = false; } catch { mapPin?.setPopupContent('Pinned area (area lookup unavailable)').openPopup(); document.querySelector('#mapStatus').textContent = 'Area pinned; address lookup is temporarily unavailable.'; document.querySelector('#applyMapPin').hidden = false; document.querySelector('#clearMapPin').hidden = false; } }; await update(latitude, longitude); mapPin.on('dragend', async (event) => { const position = event.target.getLatLng(); await update(position.lat, position.lng); }); }
function ensureMapControls() { const actions = document.querySelector('.map-actions'); if (!actions || document.querySelector('#locateMap')) return; actions.insertAdjacentHTML('afterbegin', '<button id="locateMap" type="button" class="small-button">Use my location</button>'); const mapPanel = document.querySelector('.map-panel'); mapPanel?.insertAdjacentHTML('beforeend', '<button id="applyMapPin" type="button" class="map-apply-button" hidden>Use this pinned area</button>'); document.querySelector('#mapStatus').textContent = 'Click anywhere on the map to pin an area, drag the pin to refine it, then apply the area to your filters.'; }
async function applyMapPinLegacy() { if (!mapPinLocation) return; const stateSelect = document.querySelector('#stateFilter'); const districtSelect = document.querySelector('#districtFilter'); const state = mapPinLocation.state || ''; const district = mapPinLocation.district || ''; if (state && [...stateSelect.options].some((option) => option.value === state)) stateSelect.value = state; document.querySelector('#constituencyFilter').value = ''; document.querySelector('#categoryFilter').value = ''; document.querySelector('#statusFilter').value = ''; await loadFacets(); if (district && [...districtSelect.options].some((option) => option.value === district)) districtSelect.value = district; updateDistrictLink(); await loadCatalog(); await loadMetrics(); document.querySelector('#explore').scrollIntoView({ behavior: 'smooth', block: 'start' }); document.querySelector('#mapStatus').textContent = `Dashboard filters applied for ${district || state || 'the pinned area'}.`; }
function useBrowserLocation() { if (!navigator.geolocation) { document.querySelector('#mapStatus').textContent = 'This browser does not provide location access. Click the map to pin an area.'; return; } document.querySelector('#mapStatus').textContent = 'Requesting your location…'; navigator.geolocation.getCurrentPosition(({ coords }) => { map?.setView([coords.latitude, coords.longitude], 11); void setMapPin(coords.latitude, coords.longitude); }, () => { document.querySelector('#mapStatus').textContent = 'Location access was not granted. Click the map to pin an area.'; }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 300000 }); }
function initializeMap() { if (!map) return; map.setView(INDIA_CENTER, 5); window.L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '&copy; OpenStreetMap contributors' }).addTo(map); map.on('click', (event) => setMapPin(event.latlng.lat, event.latlng.lng)); }
async function refreshMap() { if (!map) return; try { const { data } = await getJson(`/map/locations?${currentQuery()}`); mapLayers.splice(0).forEach((layer) => map.removeLayer(layer)); if (!data.points.length) { document.querySelector('#mapStatus').textContent = data.message || data.precision; return; } const bounds = []; data.points.forEach((point) => { const marker = window.L.circleMarker([point.lat, point.lon], { radius: Math.min(18, 7 + Math.log10(point.count + 1) * 4), color: '#005a9c', fillColor: '#ff9933', fillOpacity: .85, weight: 2 }); marker.bindPopup(`<strong>${escapeHtml(point.district)}</strong><br>${formatNumber(point.count)} matching works<br><small>Approximate district location</small>`).addTo(map); mapLayers.push(marker); bounds.push([point.lat, point.lon]); }); map.fitBounds(bounds, { padding: [28, 28], maxZoom: 10 }); document.querySelector('#mapStatus').textContent = `${formatNumber(data.totalMatches)} matching works · ${data.precision}`; } catch { document.querySelector('#mapStatus').textContent = 'Map location service unavailable. The table remains available.'; } }
document.querySelector('#filtersForm').addEventListener('submit', async (event) => { event.preventDefault(); document.querySelector('#explore').scrollIntoView({ behavior: 'smooth', block: 'start' }); await loadCatalog(); await loadMetrics(); });
document.querySelector('#globalSearch').addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(async () => { await loadCatalog(); await loadMetrics(); }, 300); });
document.querySelectorAll('#houseFilter, #termFilter, #stateFilter, #districtFilter, #constituencyFilter, #categoryFilter, #statusFilter').forEach((select) => select.addEventListener('change', async () => { updateDistrictLink(); await loadFacets(); await loadCatalog(); await loadMetrics(); }));
document.querySelector('#clearFilters').addEventListener('click', async () => { document.querySelector('#globalSearch').value = ''; ['houseFilter','termFilter','stateFilter','districtFilter','constituencyFilter','categoryFilter','statusFilter'].forEach((id) => { document.querySelector(`#${id}`).value = ''; }); await loadFacets(); await loadCatalog(); await loadMetrics(); });
ensureMapControls(); loadMoreButton.addEventListener('click', () => loadCatalog({ append: true })); document.querySelector('#resetMap').addEventListener('click', () => { map?.setView(INDIA_CENTER, 5); refreshMap(); }); document.querySelector('#locateMap')?.addEventListener('click', useBrowserLocation); document.querySelector('#applyMapPin')?.addEventListener('click', () => void applyMapPin()); document.querySelector('#clearMapPin')?.addEventListener('click', () => { if (mapPin) map.removeLayer(mapPin); mapPin = null; mapPinLocation = null; document.querySelector('#clearMapPin').hidden = true; document.querySelector('#applyMapPin').hidden = true; document.querySelector('#mapStatus').textContent = 'Click anywhere on the map to pin an area, or choose a state/district filter.'; }); document.querySelectorAll('.view-toggle button').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.view-toggle button').forEach((item) => item.classList.remove('active')); button.classList.add('active'); document.querySelector('.workspace-grid').classList.toggle('table-only', button.dataset.view === 'table'); setTimeout(() => map?.invalidateSize(), 50); }));
const root = document.documentElement; const fontScale = Number(localStorage.getItem('mpworks-font-scale') || 1); root.style.setProperty('--font-scale', fontScale); document.querySelectorAll('[data-font]').forEach((button) => button.addEventListener('click', () => { const current = Number(root.style.getPropertyValue('--font-scale') || 1); const next = button.dataset.font === 'increase' ? Math.min(1.25, current + .1) : button.dataset.font === 'decrease' ? Math.max(.85, current - .1) : 1; root.style.setProperty('--font-scale', next); localStorage.setItem('mpworks-font-scale', next); }));
ensureMapControls(); ensureExportControls(); updateExportLinks(); initializeMap(); updateDistrictLink(); Promise.all([loadFacets(), loadSummary(), loadCatalog(), loadMetrics()]);
async function refreshStateDistrictOptions() { while (facetLoading) await new Promise((resolve) => setTimeout(resolve, 40)); const state = value('stateFilter'); const params = new URLSearchParams(); if (state) params.set('state', state); if (value('houseFilter')) params.set('house', value('houseFilter')); if (value('termFilter')) params.set('term', value('termFilter')); try { const { data } = await getJson(`/catalog/facets?${params}`); const selected = value('districtFilter'); fillSelect('districtFilter', state ? `All districts in ${state}` : 'All districts', data.districts || [], selected); } catch { /* the main facet request owns the visible error state */ } }
document.querySelector('#stateFilter')?.addEventListener('change', () => void refreshStateDistrictOptions());
function showPinnedAreaActions() { const location = mapPinLocation; if (!location) return; const panel = document.querySelector('.map-panel'); if (!panel) return; let actions = document.querySelector('#mapAreaActions'); if (!actions) { panel.insertAdjacentHTML('beforeend', '<div id="mapAreaActions" class="map-area-actions" hidden><span>Explore this pinned area</span><a id="mapRecommendedLink" class="map-area-link recommended" href="/works.html?kind=recommended">Recommended works</a><a id="mapCompletedLink" class="map-area-link completed" href="/works.html?kind=completed">Completed works</a></div>'); actions = document.querySelector('#mapAreaActions'); } const params = new URLSearchParams(); if (location.state) params.set('state', location.state); if (location.district) params.set('district', location.district); document.querySelector('#mapRecommendedLink').href = `/works.html?kind=recommended&${params}`; document.querySelector('#mapCompletedLink').href = `/works.html?kind=completed&${params}`; actions.hidden = false; }
document.addEventListener('click', (event) => { if (event.target.closest?.('#applyMapPin')) setTimeout(showPinnedAreaActions, 80); });

function optionValueFor(select, valueToMatch) {
  const wanted = String(valueToMatch || '').trim().toLowerCase();
  return [...(select?.options || [])].find((option) => option.value.trim().toLowerCase() === wanted)?.value || '';
}

// Reverse geocoding returns title-cased names while the source facets often
// use uppercase names. Always apply the matching facet value, not just an
// exact-case string comparison, so a map pin narrows to the actual district.
async function applyMapPin() {
  if (!mapPinLocation) return;
  const stateSelect = document.querySelector('#stateFilter');
  const districtSelect = document.querySelector('#districtFilter');
  const state = optionValueFor(stateSelect, mapPinLocation.state);
  const districtName = mapPinLocation.district || mapPinLocation.area || '';
  if (state) stateSelect.value = state;
  ['constituencyFilter', 'categoryFilter', 'statusFilter'].forEach((id) => { document.querySelector(`#${id}`).value = ''; });
  districtSelect.value = '';
  await loadFacets();
  await refreshStateDistrictOptions();
  const district = optionValueFor(districtSelect, districtName);
  if (district) districtSelect.value = district;
  updateDistrictLink();
  await loadCatalog();
  await loadMetrics();
  document.querySelector('#explore').scrollIntoView({ behavior: 'smooth', block: 'start' });
  document.querySelector('#mapStatus').textContent = `Dashboard filters applied for ${district || state || 'the pinned area'}.`;
}
