import 'ux4g-web-components/styles.css';
import 'ux4g-web-components/design-system';
import '../styles.css';

const API_BASE = (import.meta.env?.VITE_MPLAD_API_BASE || window.MPLAD_API_BASE || 'http://127.0.0.1:8000/api').replace(/\/$/, '');
const root = document.querySelector('#districtRoot');
const query = new URLSearchParams(location.search);
const scope = { state: query.get('state') || '', district: query.get('district') || '', house: query.get('house') || '', term: query.get('term') || '' };
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const number = (value) => Number.isFinite(Number(value)) ? new Intl.NumberFormat('en-IN').format(Number(value)) : '—';
const money = (value) => value == null ? 'Not available' : `₹${number(value)}`;
async function getJson(path, options) { const response = await fetch(`${API_BASE}${path}`, options); if (!response.ok) throw new Error(`Request failed: ${response.status}`); return response.json(); }
function filtersQuery() { const params = new URLSearchParams(); Object.entries(scope).forEach(([key, value]) => { if (value) params.set(key, value); }); return params; }
async function getAllProjects() { const all = []; let offset = 0; let total = Infinity; while (offset < total) { const params = filtersQuery(); params.set('limit', '200'); params.set('offset', String(offset)); const payload = await getJson(`/projects?${params}`); all.push(...payload.data); total = payload.meta.total; offset += payload.meta.count; if (!payload.meta.count) break; } return all; }
function row(project, ranking) { const rank = ranking?.get(project.id); const score = rank?.score; const badge = score == null ? '<span class="rank-badge none">Not scored</span>' : `<span class="rank-badge ${score < 40 ? 'low' : ''}">${number(score)}/100</span>`; return `<tr><td><strong>${escapeHtml(project.title)}</strong><small>${escapeHtml(project.mp)}</small></td><td>${escapeHtml(project.constituency)}<small>${escapeHtml([project.block, project.villageRaw, project.state].filter(Boolean).join(' · '))}</small></td><td>${escapeHtml(project.house)}<small>${escapeHtml(project.term)}</small></td><td>${escapeHtml(project.status)}<small>${escapeHtml(project.amount)}</small></td><td>${badge}<small>${escapeHtml(rank?.label || 'AI analysis not run')}</small></td><td><a class="row-action" href="/project.html?id=${encodeURIComponent(project.id)}">View record ↗</a></td></tr>`; }
function render(projects, ranking = new Map(), sorted = false) { const ordered = sorted ? [...projects].sort((a, b) => (ranking.get(b.id)?.score ?? -1) - (ranking.get(a.id)?.score ?? -1)) : projects; root.innerHTML = `<div class="district-heading"><p class="eyebrow">MPLADS district work register</p><h1>${escapeHtml(scope.district)}</h1><p>${escapeHtml([scope.state, scope.house, scope.term].filter(Boolean).join(' · ') || 'All source scopes')}</p></div><section class="district-summary" aria-label="District summary"><div><span>Projects in register</span><strong>${number(projects.length)}</strong></div><div><span>Amount recommended</span><strong>${money(window.districtMetrics?.recommendedAmount)}</strong></div><div><span>Amount sanctioned</span><strong>${money(window.districtMetrics?.sanctionedAmount)}</strong></div><div><span>Amount used</span><strong>${money(window.districtMetrics?.usedAmount)}</strong></div><div><span>Works sanctioned</span><strong>${number(window.districtMetrics?.worksSanctioned)}</strong></div><div><span>Works completed</span><strong>${number(window.districtMetrics?.worksCompleted)}</strong></div></section><section class="district-actions"><div><h2>District-wide evidence review</h2><p>Fetch and compare source images/PDFs for every project in this district, then order records by review priority.</p></div><button id="analyzeDistrict" class="ux4g-btn-primary" type="button">Analyse all district projects</button></section><p id="districtStatus" class="district-status" aria-live="polite">${sorted ? 'Sorted by AI-assisted review priority. This is not a finding of fraud.' : 'Projects are shown in source order. Select analysis to rank them.'}</p><section class="district-table" aria-labelledby="district-projects"><div class="panel-heading"><h2 id="district-projects">All district projects</h2><span>${number(projects.length)} records</span></div><div class="district-table-wrap"><table><thead><tr><th>Project</th><th>Location</th><th>House / term</th><th>Status / amount</th><th>Review priority</th><th>Record</th></tr></thead><tbody>${ordered.map((project) => row(project, ranking)).join('')}</tbody></table></div></section>`; root.querySelector('#analyzeDistrict').addEventListener('click', () => startAnalysis(projects, ranking)); }
async function startAnalysis(projects, ranking) { const button = root.querySelector('#analyzeDistrict'); const status = root.querySelector('#districtStatus'); button.disabled = true; status.textContent = 'Queuing source evidence analysis for every project…'; try { const payload = await getJson('/district-analysis', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(scope) }); const jobId = payload.data.id; await poll(jobId, projects, ranking); } catch (error) { status.textContent = error.message; status.classList.add('error'); button.disabled = false; } }
async function poll(jobId, projects, ranking) { const status = root.querySelector('#districtStatus'); const payload = await getJson(`/district-analysis/${encodeURIComponent(jobId)}`); const job = payload.data; if (job.status === 'failed') throw new Error(job.error || 'District analysis failed'); status.textContent = `Analysed ${number(job.completed)} of ${number(job.total)} projects. Evidence is compared against each source record.`; (job.results || []).forEach((result) => ranking.set(result.projectId, result)); if (job.status !== 'completed') return setTimeout(() => poll(jobId, projects, ranking).catch((error) => { status.textContent = error.message; status.classList.add('error'); }), 2500); render(projects, ranking, true); }
async function init() { if (!scope.district) { root.innerHTML = '<div class="empty-state">Choose a district from the dashboard first. <a href="/">Return to dashboard</a>.</div>'; return; } try { const params = filtersQuery(); const metrics = await getJson(`/catalog/metrics?${params}`); window.districtMetrics = metrics.data; const projects = await getAllProjects(); render(projects); } catch (error) { root.innerHTML = `<div class="empty-state">${escapeHtml(error.message)} <a href="/">Return to dashboard</a>.</div>`; } }
const htmlRoot = document.documentElement; const savedScale = Number(localStorage.getItem('mpworks-font-scale') || 1); htmlRoot.style.setProperty('--font-scale', savedScale); document.querySelectorAll('[data-font]').forEach((button) => button.addEventListener('click', () => { const current = Number(htmlRoot.style.getPropertyValue('--font-scale') || 1); const next = button.dataset.font === 'increase' ? Math.min(1.25, current + .1) : button.dataset.font === 'decrease' ? Math.max(.85, current - .1) : 1; htmlRoot.style.setProperty('--font-scale', next); localStorage.setItem('mpworks-font-scale', String(next)); }));
init();
