import 'ux4g-web-components/styles.css';
import 'ux4g-web-components/design-system';
import '../styles.css';

const API_BASE = (import.meta.env?.VITE_MPLAD_API_BASE || window.MPLAD_API_BASE || 'https://9swhxvuz7b.execute-api.eu-north-1.amazonaws.com/api').replace(/\/$/, '');
const apiOrigin = API_BASE.replace(/\/api\/?$/, '');
const root = document.querySelector('#projectRoot');
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
const date = (value) => { const parsed = value ? new Date(value) : null; return parsed && !Number.isNaN(parsed.getTime()) ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeZone: 'UTC' }).format(parsed) : 'Not stated in source'; };
async function getJson(path, options) { const response = await fetch(`${API_BASE}${path}`, options); if (!response.ok) { let detail = ''; try { const payload = await response.json(); detail = payload.detail || payload.note || payload.error || ''; } catch {} throw new Error(`Request failed: ${response.status}${detail ? ` — ${detail}` : ''}`); } return response.json(); }
function evidenceUrl(file) { const rawUrl = file.url || file.r2Url || file.sourceUrl || ''; if (/^https?:\/\//i.test(rawUrl)) return rawUrl; if (rawUrl.startsWith('/')) return `${apiOrigin}${rawUrl}`; return ''; }
function filesMarkup(files = []) { return files.map((file) => { const url = evidenceUrl(file); const name = file.fileName || file.sourceAttachmentId || 'source attachment'; const isPdf = /^application\/pdf$/i.test(file.mimeType || '') || /\.pdf$/i.test(name); if (!url) return `<div class="evidence-file"><strong>${escapeHtml(name)}</strong><small>${escapeHtml(file.mimeType || 'evidence')} · ${file.status === 'discovered' ? 'Fetched and analysed; awaiting R2 storage' : 'Source file available; storage link pending'}</small></div>`; const kind = isPdf ? 'pdf' : 'image'; const viewLabel = isPdf ? 'View PDF here' : 'View image here'; if (isPdf) return `<div class="evidence-file"><div class="evidence-file-heading"><strong>${escapeHtml(name)}</strong><span>PDF evidence</span></div><div class="evidence-file-actions"><button class="evidence-view-button" type="button" data-open-evidence="${kind}" data-evidence-url="${escapeHtml(url)}" data-evidence-name="${escapeHtml(name)}">${viewLabel}</button><a class="evidence-view-link" href="${escapeHtml(url)}" target="_blank" rel="noreferrer">Open in new tab ↗</a></div><small>${escapeHtml(file.mimeType || 'application/pdf')}</small></div>`; return `<figure class="evidence-preview"><button class="evidence-media-trigger" type="button" data-open-evidence="${kind}" data-evidence-url="${escapeHtml(url)}" data-evidence-name="${escapeHtml(name)}" aria-label="${viewLabel}: ${escapeHtml(name)}"><img src="${escapeHtml(url)}" alt="${escapeHtml(name)}" loading="lazy" /></button><figcaption><button class="evidence-view-button" type="button" data-open-evidence="${kind}" data-evidence-url="${escapeHtml(url)}" data-evidence-name="${escapeHtml(name)}">${viewLabel}</button><a class="evidence-view-link" href="${escapeHtml(url)}" target="_blank" rel="noreferrer">New tab ↗</a><small>${escapeHtml(name)}</small></figcaption></figure>`; }).join(''); }
function ensureEvidenceViewer() { if (document.querySelector('#evidenceViewer')) return; const viewer = document.createElement('div'); viewer.id = 'evidenceViewer'; viewer.className = 'evidence-viewer'; viewer.setAttribute('role', 'dialog'); viewer.setAttribute('aria-modal', 'true'); viewer.setAttribute('aria-labelledby', 'evidenceViewerTitle'); viewer.setAttribute('aria-hidden', 'true'); viewer.hidden = true; viewer.innerHTML = '<div class="evidence-viewer-backdrop"></div><section class="evidence-viewer-panel"><header class="evidence-viewer-header"><div><p class="eyebrow">Source evidence</p><h2 id="evidenceViewerTitle">Evidence file</h2></div><button id="evidenceViewerClose" class="evidence-viewer-close" type="button" aria-label="Close evidence viewer">×</button></header><div class="evidence-viewer-content"><img id="evidenceViewerImage" alt="" hidden /><iframe id="evidenceViewerFrame" title="Source PDF viewer" loading="lazy" hidden></iframe></div><footer class="evidence-viewer-footer"><span>Official source file · verify against the source record</span><a id="evidenceViewerDownload" class="small-button" href="#" target="_blank" rel="noreferrer">Open in new tab ↗</a></footer></section>'; document.body.append(viewer); }
ensureEvidenceViewer();
function closeEvidenceViewer() { const viewer = document.querySelector('#evidenceViewer'); const image = document.querySelector('#evidenceViewerImage'); const frame = document.querySelector('#evidenceViewerFrame'); if (!viewer) return; viewer.hidden = true; viewer.setAttribute('aria-hidden', 'true'); document.body.classList.remove('evidence-viewer-open'); image?.removeAttribute('src'); frame?.removeAttribute('src'); }
function openEvidenceViewer(kind, url, name) { const viewer = document.querySelector('#evidenceViewer'); const title = document.querySelector('#evidenceViewerTitle'); const image = document.querySelector('#evidenceViewerImage'); const frame = document.querySelector('#evidenceViewerFrame'); const download = document.querySelector('#evidenceViewerDownload'); const close = document.querySelector('#evidenceViewerClose'); if (!viewer || !url) return; title.textContent = name || 'Evidence file'; download.href = url; image.hidden = kind !== 'image'; frame.hidden = kind !== 'pdf'; if (kind === 'image') image.src = url; if (kind === 'pdf') frame.src = url; viewer.hidden = false; viewer.setAttribute('aria-hidden', 'false'); document.body.classList.add('evidence-viewer-open'); close?.focus(); }
document.addEventListener('click', (event) => { const trigger = event.target.closest?.('[data-open-evidence]'); if (!trigger) return; event.preventDefault(); openEvidenceViewer(trigger.dataset.openEvidence, trigger.dataset.evidenceUrl, trigger.dataset.evidenceName); });
document.querySelector('#evidenceViewerClose')?.addEventListener('click', closeEvidenceViewer);
document.querySelector('#evidenceViewer .evidence-viewer-backdrop')?.addEventListener('click', closeEvidenceViewer);
document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && !document.querySelector('#evidenceViewer')?.hidden) closeEvidenceViewer(); });
function comparisonMarkup(value) { if (!value || value.status === 'inconclusive') return `<div class="notice">${escapeHtml(value?.reason || 'No evidence comparison was completed.')}</div>`; const issues = Array.isArray(value.possibleIssues) ? value.possibleIssues : []; return `<div class="comparison-result"><strong>Evidence comparison: ${escapeHtml(value.consistency || value.status)}</strong><p>${escapeHtml(value.summary || '')}</p>${issues.length ? `<ul>${issues.map((issue) => `<li>${escapeHtml(issue)}</li>`).join('')}</ul>` : ''}<small>This is an AI-assisted review signal. Human verification is required.</small></div>`; }
function renderAnalysis(data) { document.querySelector('#analysisResult').innerHTML = `<div class="notice">${escapeHtml(data.note || 'Evidence update received.')} ${data.persistence?.r2 === 'ready' ? 'Permanent R2 storage is enabled.' : data.status === 'processing' || data.status === 'analyzing' ? 'The page will update when analysis is ready.' : 'Permanent R2 storage is pending.'}</div>${comparisonMarkup(data.comparison)}<div class="evidence-files">${filesMarkup(data.files)}</div>`; }
async function watchEvidence(projectId) { for (let attempt = 0; attempt < 24; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 3000)); try { const { data } = await getJson(`/projects/${encodeURIComponent(projectId)}/evidence`); if (!['processing', 'analyzing'].includes(data.status)) { renderAnalysis(data); return; } renderAnalysis(data); } catch {} } document.querySelector('#analysisResult').innerHTML += '<div class="notice error-state">Evidence is still processing. Reopen this record shortly to view the completed result.</div>'; }
function render(project, evidence) { const existingFiles = evidence.files || []; root.innerHTML = `<div class="project-heading"><p class="eyebrow">MPLADS work record</p><h1>${escapeHtml(project.title)}</h1><p class="project-location">${escapeHtml(project.location)}</p><div class="project-tags"><span>${escapeHtml(project.house)}</span><span>${escapeHtml(project.term)}</span><span>${escapeHtml(project.status)}</span></div></div><div class="project-layout"><article class="project-card"><h2>Administrative details</h2><dl class="project-fields"><div><dt>Member of Parliament</dt><dd>${escapeHtml(project.mp)}</dd></div><div><dt>Constituency</dt><dd>${escapeHtml(project.constituency)}</dd></div><div><dt>State / district</dt><dd>${escapeHtml([project.state, project.district].filter(Boolean).join(' · '))}</dd></div><div><dt>Block / village</dt><dd>${escapeHtml([project.block, project.villageRaw].filter(Boolean).join(' · '))}</dd></div><div><dt>Recommended amount</dt><dd>${escapeHtml(project.amount)}</dd></div><div><dt>Recommended date</dt><dd>${escapeHtml(date(project.sourceDate))}</dd></div><div class="field-wide"><dt>Source description</dt><dd>${escapeHtml(project.raw?.description || project.raw?.WORK_DESCRIPTION || project.title)}</dd></div></dl><p class="project-note">${escapeHtml(project.summary)}</p><a class="ux4g-btn-primary project-source" href="${escapeHtml(project.sourceUrl)}" target="_blank" rel="noreferrer">Open official source ↗</a></article><aside class="project-card evidence-card"><h2>Evidence and analysis</h2><p class="project-note">Files are sourced from MPLADS/eSAKSHI and displayed from permanent R2 storage when available. They are not replaced with mock images.</p><div class="evidence-list">${(evidence.items || []).map((item) => `<div class="evidence-item"><span>${escapeHtml(item.label)}</span><strong>${escapeHtml(item.status)}</strong></div>`).join('')}</div><div class="evidence-files">${filesMarkup(existingFiles)}</div><button id="analyzeEvidence" class="ux4g-btn-primary analyze-button" type="button">Fetch images / PDFs and analyse</button><div id="analysisResult" aria-live="polite"></div></aside></div>`; root.querySelector('#analyzeEvidence').addEventListener('click', async (event) => { event.currentTarget.disabled = true; document.querySelector('#analysisResult').innerHTML = '<div class="loading-state">Starting evidence fetch and AI analysis…</div>'; try { const { data } = await getJson(`/projects/${encodeURIComponent(project.id)}/evidence/refresh`, { method: 'POST' }); renderAnalysis(data); if (['processing', 'analyzing'].includes(data.status)) void watchEvidence(project.id); } catch (error) { document.querySelector('#analysisResult').innerHTML = `<div class="notice error-state">${escapeHtml(error.message)}</div>`; } finally { event.currentTarget.disabled = false; } }); }
const query = new URLSearchParams(location.search); const id = query.get('id'); if (!id) root.innerHTML = '<div class="empty-state">No work record was selected. <a href="/">Return to dashboard</a>.</div>'; else Promise.all([getJson(`/projects/${encodeURIComponent(id)}`), getJson(`/projects/${encodeURIComponent(id)}/evidence`)]).then(([project, evidence]) => { render(project.data, evidence.data); if (['processing', 'analyzing'].includes(evidence.data.status)) void watchEvidence(id); }).catch(() => { root.innerHTML = '<div class="empty-state">This work record could not be loaded. <a href="/">Return to dashboard</a>.</div>'; });
const htmlRoot = document.documentElement; const savedScale = Number(localStorage.getItem('mpworks-font-scale') || 1); if (savedScale !== 1) htmlRoot.style.setProperty('--font-scale', savedScale); document.querySelectorAll('[data-font]').forEach((button) => button.addEventListener('click', () => { const current = Number(htmlRoot.style.getPropertyValue('--font-scale') || 1); const next = button.dataset.font === 'increase' ? Math.min(1.25, current + .1) : button.dataset.font === 'decrease' ? Math.max(.85, current - .1) : 1; htmlRoot.style.setProperty('--font-scale', next); localStorage.setItem('mpworks-font-scale', String(next)); }));
