import 'ux4g-web-components/styles.css';
import 'ux4g-web-components/design-system';
import '../styles.css';

const API_BASE = (import.meta.env?.VITE_MPLAD_API_BASE || window.MPLAD_API_BASE || 'https://9swhxvuz7b.execute-api.eu-north-1.amazonaws.com/api').replace(/\/$/, '');
const kind = new URLSearchParams(location.search).get('kind') === 'completed' ? 'completed' : 'recommended';
const pageSize = 50; let rows = [], total = 0, offset = 0, loading = false;
const $ = (id) => document.querySelector(`#${id}`); const esc = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c])); const number = (v) => Number.isFinite(Number(v)) ? new Intl.NumberFormat('en-IN').format(Number(v)) : '—';
async function get(path, options) { const response = await fetch(`${API_BASE}${path}`, options); if (!response.ok) throw new Error(`API request failed: ${response.status}`); return response.json(); }
function params() { const p = new URLSearchParams(); [['state','stateFilter'],['district','districtFilter'],['house','houseFilter'],['term','termFilter'],['query','searchFilter']].forEach(([key,id]) => { if ($(id).value) p.set(key, $(id).value); }); return p; }
function fill(id, label, values) { $(id).innerHTML = `<option value="">${label}</option>${(values || []).map((v) => `<option value="${esc(v)}">${esc(v)}</option>`).join('')}`; }
async function facets() { const { data } = await get(`/catalog/facets?${params()}`); fill('stateFilter','All States / UTs',data.states); fill('districtFilter','All districts',data.districts); fill('houseFilter','All houses',data.houses); fill('termFilter','All terms',data.terms); }
function row(project) { return `<tr><td><strong>${esc(project.title)}</strong><small>${esc(project.mp)}</small></td><td>${esc(project.district)}<small>${esc([project.villageRaw,project.state].filter(Boolean).join(' · '))}</small></td><td>${esc(project.house)}<small>${esc(project.term)}</small></td><td><span class="status-chip"><i></i>${esc(project.status)}</span><small>${esc(project.sourceDate || project.updated)}</small></td><td><strong>${esc(project.amount)}</strong><small>${number(project.attachmentCount)} evidence files</small><small>Review index: ${esc(project.riskIndex?.score ?? '—')}/100 · ${esc(project.riskIndex?.label || 'AI comparison pending')}</small></td><td><a class="row-action" href="/project.html?id=${encodeURIComponent(project.id)}">Open record ↗</a></td></tr>`; }
function render() { $('workList').innerHTML = rows.length ? `<div class="result-table-wrap"><table class="result-table"><thead><tr><th>Work description</th><th>Location</th><th>House / term</th><th>Status / date</th><th>Amount / evidence</th><th>Record</th></tr></thead><tbody>${rows.map(row).join('')}</tbody></table></div>` : '<div class="empty-state">No source records match these filters.</div>'; $('resultCount').textContent = number(total); $('pageCount').textContent = `${number(total)} ${kind} records`; $('loadMore').hidden = rows.length >= total || !rows.length; $('loadMore').textContent = rows.length < total ? `Load ${number(Math.min(pageSize,total-rows.length))} more` : 'All records loaded'; $('filterNote').textContent = `${number(total)} source records match this register. Files and AI findings are shown only when evidence exists.`; }
async function load(append = false) { if (loading) return; loading = true; if (!append) { offset = 0; rows = []; $('workList').innerHTML = '<div class="loading-state">Loading source records…</div>'; } const p=params(); p.set('limit',pageSize); p.set('offset',append ? offset : 0); try { const payload = await get(`/works/${kind}?${p}`); rows = append ? [...rows,...payload.data] : payload.data; total = payload.meta.total; offset = payload.meta.offset + payload.meta.count; render(); } catch (error) { $('workList').innerHTML = `<div class="empty-state">${esc(error.message)}</div>`; } finally { loading = false; } }
function setScale() { const root = document.documentElement; root.style.setProperty('--font-scale',Number(localStorage.getItem('mpworks-font-scale') || 1)); document.querySelectorAll('[data-font]').forEach((b) => b.addEventListener('click', () => { const current=Number(root.style.getPropertyValue('--font-scale')||1); const next=b.dataset.font==='increase'?Math.min(1.25,current+.1):b.dataset.font==='decrease'?Math.max(.85,current-.1):1; root.style.setProperty('--font-scale',next); localStorage.setItem('mpworks-font-scale',next); })); }
$('pageTitle').textContent = kind === 'completed' ? 'Completed works' : 'Recommended works'; $('breadcrumbTitle').textContent = kind === 'completed' ? 'Completed works' : 'Recommended works'; $('pageDescription').textContent = kind === 'completed' ? 'Review works marked completed or partially completed in the source register.' : 'Review works recommended through the source register, with filters for every parliamentary scope.'; $('workFilters').addEventListener('submit',(e)=>{e.preventDefault();load();}); $('clearFilters').addEventListener('click',()=>{['stateFilter','districtFilter','houseFilter','termFilter','searchFilter'].forEach((id)=>$(id).value='');load();}); $('loadMore').addEventListener('click',()=>load(true)); setScale(); facets().then(load).catch(load);
